package za.co.junghans.hszt.semin.ir;

import org.apache.log4j.Logger;
import za.co.junghans.hszt.semin.ir.analyzer.KwAnalyzer;
import za.co.junghans.hszt.semin.ir.analyzer.LuceneKwAnalyzer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;

import java.util.regex.Pattern;
import java.util.regex.Matcher;

/**
 * User: dkummer
 * Date: 12.06.11
 * Time: 22:42
 */
public class AnalyzerGui {
    private JTextArea txtInputHtml;
    private JButton btnCalculate;
    private JPanel form;
    private JTextField txtKeywords;
    private JTextArea txtResults;

    private Logger log = Logger.getLogger(AnalyzerGui.class);


    public AnalyzerGui() {
        btnCalculate.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent actionEvent) {
                //do it baby!
                log.debug("Do some calculating baby!");
                KwAnalyzer kwAnalyzer = new LuceneKwAnalyzer();
                
                //TODO: Parse txtInputHtml here
                String parsed_text = "";
                
                // 1. Only look at Contents between <body> and </body>, <title> and </title>
                Pattern p_title = Pattern.compile("<title>(.*)</title>");
                Pattern p_body = Pattern.compile("<body>(.*)</body>");
                
                Matcher m_title = p_title.matcher(txtInputHtml.getText());
                Matcher m_body = p_body.matcher("<body>lots of noise here <scrip></script><img /></body>");
                
                if (m_title.matches()) {
                	log.debug(m_title.group(1));
                	parsed_text += m_title.group(1);
                }
                
                if (m_body.matches()) {
                	log.debug("body found");
                }
                
                
                
                // 2. Ignore all tags in <tag> </tag> <tag>
              
                
                // 3. Replace tags with blank space so that contents in and outside tags don't stick together.
                // Do the regex magic here
                
                
                String result = kwAnalyzer.analyze(txtInputHtml.getText(), Arrays.asList(txtKeywords.getText().split(",")));
                txtResults.setText(result);
            }
        });
    }

    public Container getForm() {
        return form;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        form = new JPanel();
        form.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("HTML Input");
        label1.setToolTipText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(label1, gbc);
        txtInputHtml = new JTextArea();
        txtInputHtml.setEditable(true);
        txtInputHtml.setText("Insert HTML here");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        form.add(txtInputHtml, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Keywords");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(label2, gbc);
        txtKeywords = new JTextField();
        txtKeywords.setText("Keyword 1, Keyword 2");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(txtKeywords, gbc);
        btnCalculate = new JButton();
        btnCalculate.setText("Calculate!");
        btnCalculate.setMnemonic('C');
        btnCalculate.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(btnCalculate, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer4, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Results");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(label3, gbc);
        txtResults = new JTextArea();
        txtResults.setEditable(false);
        txtResults.setEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.BOTH;
        form.add(txtResults, gbc);
        label1.setLabelFor(txtInputHtml);
        label2.setLabelFor(txtKeywords);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return form;
    }
}
