package za.co.junghans.hszt.semin.ir;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.DateFormat;
import java.util.Date;

public class AnalyzeGui {
    private JPanel mainPanel;
    private JTextField txtKeywords;
    private JButton btnCalculate;
    private JTextField txtUrl;
    private JButton btnPaste;
    private JButton btnCopy;
    private JTextArea txtStatus;
    private JTextArea txtMissingKeywords;
    private JLabel txtTotalKeywords;
    private JLabel txtUniqueKeywords;
    private JLabel txtCoverage;
    private JTextArea txtFoundKeywords;

    private static AnalyzeGui _instance;

    public static AnalyzeGui getInstance() {
        if (null == _instance) {
            _instance = new AnalyzeGui();
        }
        return _instance;
    }

    private AnalyzeGui() {
        txtKeywords.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent focusEvent) {
                super.focusGained(focusEvent);
                //txtKeywords.setText("");
            }
        });
    }

    public void setActionListeners(ActionListener analyzeActionListener, ActionListener clipboardListener) {
        btnCalculate.addActionListener(analyzeActionListener);
        btnPaste.addActionListener(clipboardListener);
        btnCopy.addActionListener(clipboardListener);
    }

    public String getUrl() {
        return txtUrl.getText();
    }

    public void setUrl(String url) {
        this.txtUrl.setText(url);
    }

    public void setFoundKeywords(String foundKeywords) {
        this.txtFoundKeywords.setText(foundKeywords);
    }

    public String getFoundKeywords() {
        return this.txtFoundKeywords.getText();
    }

    public String getKeywords() {
        return txtKeywords.getText();
    }

    public void setMissingKeywords(String missingKeywords) {
        this.txtMissingKeywords.setText(missingKeywords);
    }

    public void setTotalKeywords(String totalKeywords) {
        this.txtTotalKeywords.setText(totalKeywords);
    }

    public void setUniqueKeywords(String uniqueKeywords) {
        this.txtUniqueKeywords.setText(uniqueKeywords);
    }

    public void setCoverage(String txtCoverage) {
        this.txtCoverage.setText(txtCoverage);
    }

    public void log(String text) {
        String time = DateFormat.getTimeInstance().format(new Date());
        txtStatus.append(time + ":" + text + "\n");
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:d:grow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:d:grow"));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        txtKeywords = new JTextField();
        txtKeywords.setText("keyword1, keyword2, keywordN");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(txtKeywords, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnCalculate = new JButton();
        btnCalculate.setText("Calculate Keyword Coverage");
        btnCalculate.setMnemonic('C');
        btnCalculate.setDisplayedMnemonicIndex(0);
        mainPanel.add(btnCalculate, cc.xy(1, 9));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setVerticalScrollBarPolicy(22);
        mainPanel.add(scrollPane1, cc.xy(1, 13, CellConstraints.FILL, CellConstraints.FILL));
        txtFoundKeywords = new JTextArea();
        txtFoundKeywords.setEditable(false);
        txtFoundKeywords.setRows(15);
        scrollPane1.setViewportView(txtFoundKeywords);
        txtUrl = new JTextField();
        txtUrl.setText("http://www.example.com");
        mainPanel.add(txtUrl, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnPaste = new JButton();
        btnPaste.setText("Paste");
        btnPaste.setMnemonic('P');
        btnPaste.setDisplayedMnemonicIndex(0);
        mainPanel.add(btnPaste, cc.xy(3, 3));
        btnCopy = new JButton();
        btnCopy.setText("Copy");
        btnCopy.setMnemonic('O');
        btnCopy.setDisplayedMnemonicIndex(1);
        mainPanel.add(btnCopy, cc.xy(3, 13));
        final JLabel label1 = new JLabel();
        label1.setText("URL");
        mainPanel.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setText("Keywords");
        mainPanel.add(label2, cc.xy(1, 5));
        final JLabel label3 = new JLabel();
        label3.setText("Keywords found in document");
        mainPanel.add(label3, cc.xy(1, 11));
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setVerticalScrollBarPolicy(22);
        mainPanel.add(scrollPane2, cc.xy(1, 17, CellConstraints.FILL, CellConstraints.FILL));
        txtMissingKeywords = new JTextArea();
        txtMissingKeywords.setLineWrap(true);
        txtMissingKeywords.setRows(10);
        scrollPane2.setViewportView(txtMissingKeywords);
        final JLabel label4 = new JLabel();
        label4.setText("Keywords missing");
        mainPanel.add(label4, cc.xy(1, 15));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        mainPanel.add(panel1, cc.xy(1, 19));
        panel1.setBorder(BorderFactory.createTitledBorder("Statistics"));
        final JLabel label5 = new JLabel();
        label5.setText("Total Keywords:");
        panel1.add(label5, cc.xy(1, 3));
        final JLabel label6 = new JLabel();
        label6.setText("Unique Keywords:");
        panel1.add(label6, cc.xy(1, 5));
        final JLabel label7 = new JLabel();
        label7.setText("Coverage:");
        panel1.add(label7, cc.xy(1, 7));
        txtTotalKeywords = new JLabel();
        txtTotalKeywords.setText("---");
        panel1.add(txtTotalKeywords, cc.xy(3, 3));
        txtUniqueKeywords = new JLabel();
        txtUniqueKeywords.setText("---");
        panel1.add(txtUniqueKeywords, cc.xy(3, 5));
        txtCoverage = new JLabel();
        txtCoverage.setText("---");
        panel1.add(txtCoverage, cc.xy(3, 7));
        final JScrollPane scrollPane3 = new JScrollPane();
        scrollPane3.setVerticalScrollBarPolicy(22);
        mainPanel.add(scrollPane3, cc.xy(1, 23, CellConstraints.FILL, CellConstraints.FILL));
        txtStatus = new JTextArea();
        txtStatus.setEditable(false);
        txtStatus.setEnabled(true);
        txtStatus.setLineWrap(false);
        txtStatus.setRows(10);
        txtStatus.setWrapStyleWord(false);
        scrollPane3.setViewportView(txtStatus);
        final JLabel label8 = new JLabel();
        label8.setText("Status");
        mainPanel.add(label8, cc.xy(1, 21));
        label1.setLabelFor(txtUrl);
        label2.setLabelFor(txtKeywords);
        label3.setLabelFor(txtFoundKeywords);
        label4.setLabelFor(txtMissingKeywords);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
